<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mergedModel" nsURI="https://www.tu-braunschweig.de/isf/ppuIECScenario/MergedModel"
    nsPrefix="MM">
  <eClassifiers xsi:type="ecore:EClass" name="FamilyModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" lowerBound="2"
        upperBound="-1" eType="ecore:EClass ../model_Configuration/configuration/configuration.ecore#//Configuration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../model_metric/comparisonMetric.ecore#//Metric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//FamilyModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subElements" upperBound="-1"
        eType="#//FamilyModelElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentElement" eType="#//FamilyModelElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variability" lowerBound="1"
        eType="#//VariabilityCategory" defaultValueLiteral="UNDEFINED"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origins" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="similarityValues" upperBound="-1"
        eType="#//SimilarityValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variations" upperBound="-1"
        eType="#//Variation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariabilityCategory">
    <eLiterals name="MANDATORY"/>
    <eLiterals name="ALTERNATIVE" value="1"/>
    <eLiterals name="OPTIONAL" value="2"/>
    <eLiterals name="UNDEFINED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimilarityValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstOrigin" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondOrigin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="properties" lowerBound="1"
        upperBound="-1">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
