<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MergingContainer" nsURI="http://www.example.org/ppuIECScenario/MergingContainer"
    nsPrefix="MC">
  <eClassifiers xsi:type="ecore:EClass" name="MergingContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSubsystem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isPartOf" upperBound="-1"
        eType="#//SourceVariant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceVariant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
