//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.06 at 10:56:18 AM MEZ 
//

package de.tu_bs.isf.familymining.ppu_iec.export.xsd_objects;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * List of additional data elements used in the document with description
 * 
 * <p>
 * Java class for addDataInfo complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="addDataInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="info" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="description" type="{http://www.plcopen.org/xml/tc6_0201}formattedText" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="vendor" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addDataInfo", propOrder = { "info" })
public class AddDataInfo {

	protected List<AddDataInfo.Info> info;

	/**
	 * Gets the value of the info property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the info property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInfo().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link AddDataInfo.Info }
	 * 
	 * 
	 */
	public List<AddDataInfo.Info> getInfo() {
		if (info == null) {
			info = new ArrayList<AddDataInfo.Info>();
		}
		return this.info;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="description" type="{http://www.plcopen.org/xml/tc6_0201}formattedText" minOccurs="0"/>
	 *       &lt;/sequence>
	 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
	 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *       &lt;attribute name="vendor" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "description" })
	public static class Info {

		protected FormattedText description;
		@XmlAttribute(required = true)
		@XmlSchemaType(name = "anyURI")
		protected String name;
		@XmlAttribute
		protected BigDecimal version;
		@XmlAttribute(required = true)
		@XmlSchemaType(name = "anyURI")
		protected String vendor;

		/**
		 * Gets the value of the description property.
		 * 
		 * @return possible object is {@link FormattedText }
		 * 
		 */
		public FormattedText getDescription() {
			return description;
		}

		/**
		 * Sets the value of the description property.
		 * 
		 * @param value allowed object is {@link FormattedText }
		 * 
		 */
		public void setDescription(FormattedText value) {
			this.description = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setName(String value) {
			this.name = value;
		}

		/**
		 * Gets the value of the version property.
		 * 
		 * @return possible object is {@link BigDecimal }
		 * 
		 */
		public BigDecimal getVersion() {
			return version;
		}

		/**
		 * Sets the value of the version property.
		 * 
		 * @param value allowed object is {@link BigDecimal }
		 * 
		 */
		public void setVersion(BigDecimal value) {
			this.version = value;
		}

		/**
		 * Gets the value of the vendor property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getVendor() {
			return vendor;
		}

		/**
		 * Sets the value of the vendor property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setVendor(String value) {
			this.vendor = value;
		}

	}

}
