//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.06 at 10:56:18 AM MEZ 
//


package de.tu_bs.isf.familymining.ppu_iec.export.xsd_objects;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A generic data type
 * 
 * <p>Java class for dataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;group ref="{http://www.plcopen.org/xml/tc6_0201}elementaryTypes"/>
 *         &lt;group ref="{http://www.plcopen.org/xml/tc6_0201}derivedTypes"/>
 *         &lt;group ref="{http://www.plcopen.org/xml/tc6_0201}extended"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataType", propOrder = {
    "bool",
    "_byte",
    "word",
    "dword",
    "lword",
    "sint",
    "_int",
    "dint",
    "lint",
    "usint",
    "uint",
    "udint",
    "ulint",
    "real",
    "lreal",
    "time",
    "date",
    "dt",
    "tod",
    "string",
    "wstring",
    "any",
    "anyderived",
    "anyelementary",
    "anymagnitude",
    "anynum",
    "anyreal",
    "anyint",
    "anybit",
    "anystring",
    "anydate",
    "array",
    "derived",
    "_enum",
    "struct",
    "subrangeSigned",
    "subrangeUnsigned",
    "pointer"
})
public class DataType {

    @XmlElement(name = "BOOL")
    protected Object bool;
    @XmlElement(name = "BYTE")
    protected Object _byte;
    @XmlElement(name = "WORD")
    protected Object word;
    @XmlElement(name = "DWORD")
    protected Object dword;
    @XmlElement(name = "LWORD")
    protected Object lword;
    @XmlElement(name = "SINT")
    protected Object sint;
    @XmlElement(name = "INT")
    protected Object _int;
    @XmlElement(name = "DINT")
    protected Object dint;
    @XmlElement(name = "LINT")
    protected Object lint;
    @XmlElement(name = "USINT")
    protected Object usint;
    @XmlElement(name = "UINT")
    protected Object uint;
    @XmlElement(name = "UDINT")
    protected Object udint;
    @XmlElement(name = "ULINT")
    protected Object ulint;
    @XmlElement(name = "REAL")
    protected Object real;
    @XmlElement(name = "LREAL")
    protected Object lreal;
    @XmlElement(name = "TIME")
    protected Object time;
    @XmlElement(name = "DATE")
    protected Object date;
    @XmlElement(name = "DT")
    protected Object dt;
    @XmlElement(name = "TOD")
    protected Object tod;
    protected DataType.String string;
    protected DataType.Wstring wstring;
    @XmlElement(name = "ANY")
    protected Object any;
    @XmlElement(name = "ANY_DERIVED")
    protected Object anyderived;
    @XmlElement(name = "ANY_ELEMENTARY")
    protected Object anyelementary;
    @XmlElement(name = "ANY_MAGNITUDE")
    protected Object anymagnitude;
    @XmlElement(name = "ANY_NUM")
    protected Object anynum;
    @XmlElement(name = "ANY_REAL")
    protected Object anyreal;
    @XmlElement(name = "ANY_INT")
    protected Object anyint;
    @XmlElement(name = "ANY_BIT")
    protected Object anybit;
    @XmlElement(name = "ANY_STRING")
    protected Object anystring;
    @XmlElement(name = "ANY_DATE")
    protected Object anydate;
    protected DataType.Array array;
    protected DataType.Derived derived;
    @XmlElement(name = "enum")
    protected DataType.Enum _enum;
    protected VarListPlain struct;
    protected DataType.SubrangeSigned subrangeSigned;
    protected DataType.SubrangeUnsigned subrangeUnsigned;
    protected DataType.Pointer pointer;

    /**
     * Gets the value of the bool property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBOOL() {
        return bool;
    }

    /**
     * Sets the value of the bool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBOOL(Object value) {
        this.bool = value;
    }

    /**
     * Gets the value of the byte property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBYTE() {
        return _byte;
    }

    /**
     * Sets the value of the byte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBYTE(Object value) {
        this._byte = value;
    }

    /**
     * Gets the value of the word property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getWORD() {
        return word;
    }

    /**
     * Sets the value of the word property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setWORD(Object value) {
        this.word = value;
    }

    /**
     * Gets the value of the dword property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDWORD() {
        return dword;
    }

    /**
     * Sets the value of the dword property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDWORD(Object value) {
        this.dword = value;
    }

    /**
     * Gets the value of the lword property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLWORD() {
        return lword;
    }

    /**
     * Sets the value of the lword property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLWORD(Object value) {
        this.lword = value;
    }

    /**
     * Gets the value of the sint property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSINT() {
        return sint;
    }

    /**
     * Sets the value of the sint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSINT(Object value) {
        this.sint = value;
    }

    /**
     * Gets the value of the int property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getINT() {
        return _int;
    }

    /**
     * Sets the value of the int property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setINT(Object value) {
        this._int = value;
    }

    /**
     * Gets the value of the dint property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDINT() {
        return dint;
    }

    /**
     * Sets the value of the dint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDINT(Object value) {
        this.dint = value;
    }

    /**
     * Gets the value of the lint property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLINT() {
        return lint;
    }

    /**
     * Sets the value of the lint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLINT(Object value) {
        this.lint = value;
    }

    /**
     * Gets the value of the usint property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUSINT() {
        return usint;
    }

    /**
     * Sets the value of the usint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUSINT(Object value) {
        this.usint = value;
    }

    /**
     * Gets the value of the uint property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUINT() {
        return uint;
    }

    /**
     * Sets the value of the uint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUINT(Object value) {
        this.uint = value;
    }

    /**
     * Gets the value of the udint property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUDINT() {
        return udint;
    }

    /**
     * Sets the value of the udint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUDINT(Object value) {
        this.udint = value;
    }

    /**
     * Gets the value of the ulint property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getULINT() {
        return ulint;
    }

    /**
     * Sets the value of the ulint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setULINT(Object value) {
        this.ulint = value;
    }

    /**
     * Gets the value of the real property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getREAL() {
        return real;
    }

    /**
     * Sets the value of the real property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setREAL(Object value) {
        this.real = value;
    }

    /**
     * Gets the value of the lreal property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLREAL() {
        return lreal;
    }

    /**
     * Sets the value of the lreal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLREAL(Object value) {
        this.lreal = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTIME() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTIME(Object value) {
        this.time = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDATE() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDATE(Object value) {
        this.date = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDT() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDT(Object value) {
        this.dt = value;
    }

    /**
     * Gets the value of the tod property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTOD() {
        return tod;
    }

    /**
     * Sets the value of the tod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTOD(Object value) {
        this.tod = value;
    }

    /**
     * Gets the value of the string property.
     * 
     * @return
     *     possible object is
     *     {@link DataType.String }
     *     
     */
    public DataType.String getString() {
        return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType.String }
     *     
     */
    public void setString(DataType.String value) {
        this.string = value;
    }

    /**
     * Gets the value of the wstring property.
     * 
     * @return
     *     possible object is
     *     {@link DataType.Wstring }
     *     
     */
    public DataType.Wstring getWstring() {
        return wstring;
    }

    /**
     * Sets the value of the wstring property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType.Wstring }
     *     
     */
    public void setWstring(DataType.Wstring value) {
        this.wstring = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getANY() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setANY(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the anyderived property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getANYDERIVED() {
        return anyderived;
    }

    /**
     * Sets the value of the anyderived property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setANYDERIVED(Object value) {
        this.anyderived = value;
    }

    /**
     * Gets the value of the anyelementary property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getANYELEMENTARY() {
        return anyelementary;
    }

    /**
     * Sets the value of the anyelementary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setANYELEMENTARY(Object value) {
        this.anyelementary = value;
    }

    /**
     * Gets the value of the anymagnitude property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getANYMAGNITUDE() {
        return anymagnitude;
    }

    /**
     * Sets the value of the anymagnitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setANYMAGNITUDE(Object value) {
        this.anymagnitude = value;
    }

    /**
     * Gets the value of the anynum property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getANYNUM() {
        return anynum;
    }

    /**
     * Sets the value of the anynum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setANYNUM(Object value) {
        this.anynum = value;
    }

    /**
     * Gets the value of the anyreal property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getANYREAL() {
        return anyreal;
    }

    /**
     * Sets the value of the anyreal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setANYREAL(Object value) {
        this.anyreal = value;
    }

    /**
     * Gets the value of the anyint property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getANYINT() {
        return anyint;
    }

    /**
     * Sets the value of the anyint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setANYINT(Object value) {
        this.anyint = value;
    }

    /**
     * Gets the value of the anybit property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getANYBIT() {
        return anybit;
    }

    /**
     * Sets the value of the anybit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setANYBIT(Object value) {
        this.anybit = value;
    }

    /**
     * Gets the value of the anystring property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getANYSTRING() {
        return anystring;
    }

    /**
     * Sets the value of the anystring property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setANYSTRING(Object value) {
        this.anystring = value;
    }

    /**
     * Gets the value of the anydate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getANYDATE() {
        return anydate;
    }

    /**
     * Sets the value of the anydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setANYDATE(Object value) {
        this.anydate = value;
    }

    /**
     * Gets the value of the array property.
     * 
     * @return
     *     possible object is
     *     {@link DataType.Array }
     *     
     */
    public DataType.Array getArray() {
        return array;
    }

    /**
     * Sets the value of the array property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType.Array }
     *     
     */
    public void setArray(DataType.Array value) {
        this.array = value;
    }

    /**
     * Gets the value of the derived property.
     * 
     * @return
     *     possible object is
     *     {@link DataType.Derived }
     *     
     */
    public DataType.Derived getDerived() {
        return derived;
    }

    /**
     * Sets the value of the derived property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType.Derived }
     *     
     */
    public void setDerived(DataType.Derived value) {
        this.derived = value;
    }

    /**
     * Gets the value of the enum property.
     * 
     * @return
     *     possible object is
     *     {@link DataType.Enum }
     *     
     */
    public DataType.Enum getEnum() {
        return _enum;
    }

    /**
     * Sets the value of the enum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType.Enum }
     *     
     */
    public void setEnum(DataType.Enum value) {
        this._enum = value;
    }

    /**
     * Gets the value of the struct property.
     * 
     * @return
     *     possible object is
     *     {@link VarListPlain }
     *     
     */
    public VarListPlain getStruct() {
        return struct;
    }

    /**
     * Sets the value of the struct property.
     * 
     * @param value
     *     allowed object is
     *     {@link VarListPlain }
     *     
     */
    public void setStruct(VarListPlain value) {
        this.struct = value;
    }

    /**
     * Gets the value of the subrangeSigned property.
     * 
     * @return
     *     possible object is
     *     {@link DataType.SubrangeSigned }
     *     
     */
    public DataType.SubrangeSigned getSubrangeSigned() {
        return subrangeSigned;
    }

    /**
     * Sets the value of the subrangeSigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType.SubrangeSigned }
     *     
     */
    public void setSubrangeSigned(DataType.SubrangeSigned value) {
        this.subrangeSigned = value;
    }

    /**
     * Gets the value of the subrangeUnsigned property.
     * 
     * @return
     *     possible object is
     *     {@link DataType.SubrangeUnsigned }
     *     
     */
    public DataType.SubrangeUnsigned getSubrangeUnsigned() {
        return subrangeUnsigned;
    }

    /**
     * Sets the value of the subrangeUnsigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType.SubrangeUnsigned }
     *     
     */
    public void setSubrangeUnsigned(DataType.SubrangeUnsigned value) {
        this.subrangeUnsigned = value;
    }

    /**
     * Gets the value of the pointer property.
     * 
     * @return
     *     possible object is
     *     {@link DataType.Pointer }
     *     
     */
    public DataType.Pointer getPointer() {
        return pointer;
    }

    /**
     * Sets the value of the pointer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType.Pointer }
     *     
     */
    public void setPointer(DataType.Pointer value) {
        this.pointer = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dimension" type="{http://www.plcopen.org/xml/tc6_0201}rangeSigned" maxOccurs="unbounded"/>
     *         &lt;element name="baseType" type="{http://www.plcopen.org/xml/tc6_0201}dataType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dimension",
        "baseType"
    })
    public static class Array {

        @XmlElement(required = true)
        protected List<RangeSigned> dimension;
        @XmlElement(required = true)
        protected DataType baseType;

        /**
         * Gets the value of the dimension property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dimension property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDimension().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RangeSigned }
         * 
         * 
         */
        public List<RangeSigned> getDimension() {
            if (dimension == null) {
                dimension = new ArrayList<RangeSigned>();
            }
            return this.dimension;
        }

        /**
         * Gets the value of the baseType property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getBaseType() {
            return baseType;
        }

        /**
         * Sets the value of the baseType property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setBaseType(DataType value) {
            this.baseType = value;
        }

    }


    /**
     * The user defined alias type
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="addData" type="{http://www.plcopen.org/xml/tc6_0201}addData" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "addData"
    })
    public static class Derived {

        protected AddData addData;
        @XmlAttribute(required = true)
        protected java.lang.String name;

        /**
         * Gets the value of the addData property.
         * 
         * @return
         *     possible object is
         *     {@link AddData }
         *     
         */
        public AddData getAddData() {
            return addData;
        }

        /**
         * Sets the value of the addData property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddData }
         *     
         */
        public void setAddData(AddData value) {
            this.addData = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setName(java.lang.String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="values">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="value">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="baseType" type="{http://www.plcopen.org/xml/tc6_0201}dataType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "values",
        "baseType"
    })
    public static class Enum {

        @XmlElement(required = true)
        protected DataType.Enum.Values values;
        protected DataType baseType;

        /**
         * Gets the value of the values property.
         * 
         * @return
         *     possible object is
         *     {@link DataType.Enum.Values }
         *     
         */
        public DataType.Enum.Values getValues() {
            return values;
        }

        /**
         * Sets the value of the values property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType.Enum.Values }
         *     
         */
        public void setValues(DataType.Enum.Values value) {
            this.values = value;
        }

        /**
         * Gets the value of the baseType property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getBaseType() {
            return baseType;
        }

        /**
         * Sets the value of the baseType property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setBaseType(DataType value) {
            this.baseType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="value">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Values {

            @XmlElement(required = true)
            protected List<DataType.Enum.Values.Value> value;

            /**
             * Gets the value of the value property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the value property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getValue().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DataType.Enum.Values.Value }
             * 
             * 
             */
            public List<DataType.Enum.Values.Value> getValue() {
                if (value == null) {
                    value = new ArrayList<DataType.Enum.Values.Value>();
                }
                return this.value;
            }


            /**
             * An enumeration value used to build up enumeration types
             * 
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Value {

                @XmlAttribute(required = true)
                protected java.lang.String name;
                @XmlAttribute
                protected java.lang.String value;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String }
                 *     
                 */
                public java.lang.String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String }
                 *     
                 */
                public void setName(java.lang.String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String }
                 *     
                 */
                public java.lang.String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String }
                 *     
                 */
                public void setValue(java.lang.String value) {
                    this.value = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="baseType" type="{http://www.plcopen.org/xml/tc6_0201}dataType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "baseType"
    })
    public static class Pointer {

        @XmlElement(required = true)
        protected DataType baseType;

        /**
         * Gets the value of the baseType property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getBaseType() {
            return baseType;
        }

        /**
         * Sets the value of the baseType property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setBaseType(DataType value) {
            this.baseType = value;
        }

    }


    /**
     * The single byte character string type
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class String {

        @XmlAttribute
        protected java.lang.String length;

        /**
         * Gets the value of the length property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getLength() {
            return length;
        }

        /**
         * Sets the value of the length property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setLength(java.lang.String value) {
            this.length = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="range" type="{http://www.plcopen.org/xml/tc6_0201}rangeSigned"/>
     *         &lt;element name="baseType" type="{http://www.plcopen.org/xml/tc6_0201}dataType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "range",
        "baseType"
    })
    public static class SubrangeSigned {

        @XmlElement(required = true)
        protected RangeSigned range;
        @XmlElement(required = true)
        protected DataType baseType;

        /**
         * Gets the value of the range property.
         * 
         * @return
         *     possible object is
         *     {@link RangeSigned }
         *     
         */
        public RangeSigned getRange() {
            return range;
        }

        /**
         * Sets the value of the range property.
         * 
         * @param value
         *     allowed object is
         *     {@link RangeSigned }
         *     
         */
        public void setRange(RangeSigned value) {
            this.range = value;
        }

        /**
         * Gets the value of the baseType property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getBaseType() {
            return baseType;
        }

        /**
         * Sets the value of the baseType property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setBaseType(DataType value) {
            this.baseType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="range" type="{http://www.plcopen.org/xml/tc6_0201}rangeUnsigned"/>
     *         &lt;element name="baseType" type="{http://www.plcopen.org/xml/tc6_0201}dataType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "range",
        "baseType"
    })
    public static class SubrangeUnsigned {

        @XmlElement(required = true)
        protected RangeUnsigned range;
        @XmlElement(required = true)
        protected DataType baseType;

        /**
         * Gets the value of the range property.
         * 
         * @return
         *     possible object is
         *     {@link RangeUnsigned }
         *     
         */
        public RangeUnsigned getRange() {
            return range;
        }

        /**
         * Sets the value of the range property.
         * 
         * @param value
         *     allowed object is
         *     {@link RangeUnsigned }
         *     
         */
        public void setRange(RangeUnsigned value) {
            this.range = value;
        }

        /**
         * Gets the value of the baseType property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getBaseType() {
            return baseType;
        }

        /**
         * Sets the value of the baseType property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setBaseType(DataType value) {
            this.baseType = value;
        }

    }


    /**
     * The wide character (WORD) string type
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Wstring {

        @XmlAttribute
        protected java.lang.String length;

        /**
         * Gets the value of the length property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getLength() {
            return length;
        }

        /**
         * Sets the value of the length property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setLength(java.lang.String value) {
            this.length = value;
        }

    }

}
