//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.06 at 10:56:18 AM MEZ 
//


package de.tu_bs.isf.familymining.ppu_iec.export.xsd_objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;



/**
 * List of variable declarations that share the same memory attributes (CONSTANT, RETAIN, NON_RETAIN, PERSISTENT)
 * 
 * <p>Java class for varList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="varList">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.plcopen.org/xml/tc6_0201}varListPlain">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="constant" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="retain" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="nonretain" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="persistent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="nonpersistent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "varList")
@XmlSeeAlso({
    de.tu_bs.isf.familymining.ppu_iec.export.xsd_objects.Project.Types.Pous.Pou.Interface.LocalVars.class,
    de.tu_bs.isf.familymining.ppu_iec.export.xsd_objects.Project.Types.Pous.Pou.Interface.TempVars.class,
    de.tu_bs.isf.familymining.ppu_iec.export.xsd_objects.Project.Types.Pous.Pou.Interface.InputVars.class,
    de.tu_bs.isf.familymining.ppu_iec.export.xsd_objects.Project.Types.Pous.Pou.Interface.OutputVars.class,
    de.tu_bs.isf.familymining.ppu_iec.export.xsd_objects.Project.Types.Pous.Pou.Interface.InOutVars.class,
    de.tu_bs.isf.familymining.ppu_iec.export.xsd_objects.Project.Types.Pous.Pou.Interface.ExternalVars.class,
    de.tu_bs.isf.familymining.ppu_iec.export.xsd_objects.Project.Types.Pous.Pou.Interface.GlobalVars.class
})
public class VarList
    extends VarListPlain
{

    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected Boolean constant;
    @XmlAttribute
    protected Boolean retain;
    @XmlAttribute
    protected Boolean nonretain;
    @XmlAttribute
    protected Boolean persistent;
    @XmlAttribute
    protected Boolean nonpersistent;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the constant property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConstant() {
        if (constant == null) {
            return false;
        } else {
            return constant;
        }
    }

    /**
     * Sets the value of the constant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConstant(Boolean value) {
        this.constant = value;
    }

    /**
     * Gets the value of the retain property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRetain() {
        if (retain == null) {
            return false;
        } else {
            return retain;
        }
    }

    /**
     * Sets the value of the retain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRetain(Boolean value) {
        this.retain = value;
    }

    /**
     * Gets the value of the nonretain property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNonretain() {
        if (nonretain == null) {
            return false;
        } else {
            return nonretain;
        }
    }

    /**
     * Sets the value of the nonretain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNonretain(Boolean value) {
        this.nonretain = value;
    }

    /**
     * Gets the value of the persistent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPersistent() {
        if (persistent == null) {
            return false;
        } else {
            return persistent;
        }
    }

    /**
     * Sets the value of the persistent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPersistent(Boolean value) {
        this.persistent = value;
    }

    /**
     * Gets the value of the nonpersistent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNonpersistent() {
        if (nonpersistent == null) {
            return false;
        } else {
            return nonpersistent;
        }
    }

    /**
     * Sets the value of the nonpersistent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNonpersistent(Boolean value) {
        this.nonpersistent = value;
    }

}
