<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="comparisonMetric" nsURI="https://www.tu-braunschweig.de/isf/ppuIECScenario/metric"
    nsPrefix="C">
  <eClassifiers xsi:type="ecore:EClass" name="Metric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isWeighted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comparisonattribute" upperBound="-1"
        eType="#//ComparisonAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childAttributes" upperBound="-1"
        eType="#//ComparisonAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentAttribute" eType="#//ComparisonAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetType" eType="#//ComparisonTarget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonTarget">
    <eLiterals name="Variant"/>
    <eLiterals name="POU" value="1"/>
    <eLiterals name="Action" value="2"/>
    <eLiterals name="Variable" value="3"/>
    <eLiterals name="StructuredText" value="4"/>
    <eLiterals name="SequentialFunctionChart" value="5"/>
    <eLiterals name="LadderDiagram" value="6"/>
    <eLiterals name="InstructionList" value="7"/>
    <eLiterals name="FunctionBlockDiagram" value="8"/>
  </eClassifiers>
</ecore:EPackage>
